### PR TITLE
Update nvidia docker container to have perception dependencies installed.

### PR DESCRIPTION
**Pull request by calvertdw**

### CODE REVIEW

**Comment by ds58** [comment]
No one uses this so I am not sure we should keep it

**Comment by calvertdw** [comment]
> No one uses this so I am not sure we should keep it

This enabled me get ZED SDK installed on Arch by being able to copy out the resulting `/usr/local/zed` folder. Otherwise, I can't run/test/develop perception.

**Review by ds58 — APPROVED** [review]
Probably need to bump the base image version in the other containers e.g. `docker/nvidia-ros2-ide` or delete these if we don't intend to maintain them.

**Comment by calvertdw** [comment]
> Probably need to bump the base image version in the other containers e.g. `docker/nvidia-ros2-ide` or delete these if we don't intend to maintain them.

I kind of don't want to spend the time right now on that since it's not towards anything, but I think those are useful reference and worth keeping around.

**Pull request merged**
